function [] = printTablesToTexFile(fid, xBegin, xEnd, startEps, finishEps)
    printTableForMethodToTexFile(fid, @bitSearch, ...  
                                 native2unicode('Поразрядный поиск'), ...
                                 @f, xBegin, xEnd, startEps, finishEps);
    printTableForMethodToTexFile(fid, @goldSection, ...
                                 native2unicode('Золотое сечение'), ...
                                 @f, xBegin, xEnd, startEps, finishEps);
    printTableForMethodToTexFile(fid, @quadraticInterpolation, ...
                                 native2unicode('Модифицированный метод квадратичной интерполяции'), ...
                                 @f, xBegin, xEnd, startEps, finishEps);
    printTableForMethodToTexFile(fid, @methodOfNewton, ...
                                 native2unicode('Модифицированный метод Ньютона'), ...
                                 @f, 0.4, 0.7, startEps, finishEps); % hacking hard code
end

